name: als-finder
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - geopandas
  - shapely
  - pyproj
  - pyogrio
  - pdal
  - python-pdal
  - requests
  - click
  - python-dotenv
  - tqdm
  - pytest
  - setuptools_scm
  - pip
  - pip:
    - -e .
