name: als-finder-binder
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - pdal
  - python-pdal
  - geopandas
  - shapely
  - pyproj
  - pyogrio
  - fiona
  - laspy
  - pystac
  - stac-validator
  - requests
  - boto3
  - click
  - python-dotenv
  - tqdm
  - psutil
  - pyyaml
  - matplotlib
  - folium
  - ipykernel
  - jupyterlab
  - pip
  - pip:
      - -e .
