name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Mandatory for PyPI OIDC Trusted Publishing
      contents: write  # Needed for setuptools_scm to parse Git tags

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for setuptools_scm to detect the Git Tag history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install build tools natively
      run: python -m pip install build

    - name: Build Universal Python Wheel
      run: python -m build

    - name: Publish direct to PyPI Trusted Publisher
      uses: pypa/gh-action-pypi-publish@release/v1
