name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    
    # Specifies that the job requires permission to request an OIDC token
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for setuptools_scm to get git tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: python -m pip install --upgrade pip build

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No password or username needed. It uses Trusted Publishing (OIDC).
